ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from products.views import products
from products.views import single
from carts.views import viewCart, update_cart
from orders.views import checkout
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

 
urlpatterns = [
    url(r'^$', products, name='products'),
    path('admin/', admin.site.urls),
    url(r'^products/$', products, name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', single, name='single_product'),
    url(r'^cart/$', viewCart, name='viewCart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', update_cart, name='update_cart'),
    url(r'^checkout/$', checkout, name='checkout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
	types = (
		("featured", "Featured"),
		("on sale", "On Sale"),
		("new arrival", "New Arrival")
		)
	product_name = models.CharField(max_length=500, blank=False, null=False)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=30)
	sale = models.DecimalField(max_digits=100, decimal_places=2, default=30)
	stock = models.DecimalField(max_digits=100, decimal_places=2, default=30)
	category = models.CharField(max_length=400, choices=types, default="Featured")
	description = models.TextField(default="")
	slug = models.SlugField(default="")
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.product_name
	class Meta:
		unique_together = ("product_name", "slug")	



class ProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete= models.CASCADE)
	image = models.ImageField(upload_to="products/images/", blank=True)
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=True)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.product.product_name

templates/products_template/home.html
{% extends 'base.html' %}
{% load static %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'owl-carousel/owl.carousel.min.js' %}"></script>    
    
{% block content %}

    <section class="header">
        {% include 'products_template/side_navbar.html' %}
        <div class="slider">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                
                <div class="carousel-inner">
                    {% load static %}
                    <div class="carousel-item active">
                    <img src="{% static 'img/004.jpg' %}" class="d-block w-100">
                    </div>
                    <div class="carousel-item">
                    <img src="{% static 'img/slider1.jpg' %}" class="d-block w-100">
                    </div>
                    <div class="carousel-item">
                    <img src="{% static 'img/004.jpg' %}" class="d-block w-100">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                <ol class="carousel-indicators">
                    <li data-target="#slider" data-slide-to="0" class="active"></li>
                    <li data-target="#slider" data-slide-to="1"></li>
                    <li data-target="#slider" data-slide-to="2"></li>
                </ol>      
            </div>
        </div>
    </section>

    <section class="featured-categories">
        <div class="container">
            <div class="row">
            {% for item in products %}
            {% if item.category == "featured" %}
            {% for image in item.productimage_set.all %}
                <div class="col-md-4">
                    {% if image.thumbnail == True and image.active == True %}
                    <a href="{% url 'single_product' item.slug %}">
                        <img src="/media/{{image.image}}">
                    </a>
                    {% endif %}
                    <div class="product-bottom text-center">
                        <a href="{% url 'single_product' item.slug %}">
                        <h6>{{item.product_name}}</h6>
                        </a>
                        <h5>BDT {{item.price}}</h5>
                    </div>
                </div>
                {% endfor %}
                
            {% endif %}          
            {% endfor %}    
            </div>
        </div>
    </section>

    <section class="on-sale">
        <div class="container">
            <div class="title-box">
                <h2>On Sale</h2>
            </div>
            <div class="row">
                {% for item in products %}
                {% if item.category == "on sale" %}
                <div class="col-md-3">
                    {% for image in item.productimage_set.all %}    
                        <div class="product-top">
                            {% if image.thumbnail == True and image.active == True %}
                            <a href="{% url 'single_product' item.slug %}">
                            <img src="/media/{{image.image}}">
                            </a>
                            {% endif %}
                    {% endfor %}        
                            <div class="overlay-right">
                                <a href="{% url 'single_product' item.slug %}">
                                <button type="button" class="btn btn-secondary" title="Quick Shop">
                                    <i class="fa fa-eye"></i>
                                </button>
                                </a>
                                <button type="button" class="btn btn-secondary" title="Quick Shop">
                                    <i class="fa fa-heart-o"></i>
                                </button>
                                <a href="{% url 'update_cart' item.slug %}">
                                <button type="button" class="btn btn-secondary" title="Quick Shop">
                                    <i class="fa fa-shopping-cart"></i>
                                </button>
                                </a>
                            </div>
                            <div class="overlay-left">
                                    {% with key=item.id %}
                                    <span style="color: red;">{{ percentage_discount|dict_key:key }}%</span>                           
                                    {% endwith %}
                            </div>
                            <div class="product-bottom text-center">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-half-o"></i>
                                <a href="{% url 'single_product' item.slug %}">
                                <h6>{{item.product_name}}</h6>
                                </a>
                                <h6 style="color: brown;">Price: BDT {{item.price}}</h6>
                                <h5 style="color: blue;">Sale: BDT {{item.sale}}</h5>
                            </div>
                        </div>
                </div>        
                {% endif %}
                {% endfor %}                                     
            </div>
        </div>                
    </section>

    <section class="new-product">
        <div class="container">
            <div class="title-box">
                <h2>New Arrivals</h2>
            </div>
            <div class="row">
                {% for item in products %}
                {% if item.category == "new arrival" %}
                <div class="col-md-3">
                    {% for image in item.productimage_set.all %}    
                        <div class="product-top">
                            {% if image.thumbnail == True and image.active == True %}
                            <a href="{% url 'single_product' item.slug %}">
                            <img src="/media/{{image.image}}">
                            </a>
                            {% endif %}
                    {% endfor %}        
                        <div class="overlay-right">
                            <button type="button" class="btn btn-secondary" title="Quick Shop">
                                <i class="fa fa-eye"></i>
                            </button>
                            <button type="button" class="btn btn-secondary" title="Quick Shop">
                                <i class="fa fa-heart-o"></i>
                            </button>
                            <button type="button" class="btn btn-secondary" title="Quick Shop">
                                <i class="fa fa-shopping-cart"></i>
                            </button>
                        </div>
                        <div class="product-bottom text-center">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                            <a href="{% url 'single_product' item.slug %}">
                            <h6>{{item.product_name}}</h6>
                            </a>
                            <h6>BDT {{item.price}}</h6>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}                
                      
            </div>
        </div>
    </section>
{% endblock %}

    {% block script %}
    function openMenu(){
        document.getElementById("side-menu").style.display="block";
        document.getElementById("menu-btn").style.display="none";
        document.getElementById("close-btn").style.display="block";
    }
    function closeMenu(){
        document.getElementById("side-menu").style.display="none";
        document.getElementById("menu-btn").style.display="block";
        document.getElementById("close-btn").style.display="none";
    }

    $(document).ready(function(){
        $(".owl-carousel").owlCarousel({
            items: 1,
            nav: true,
            loop: true,
            autoplay: true
        });
        });

{% endblock %}

templates/products_template/side_navbar.html
<div class="side-menu" id="side-menu">
    <ul>
        <li>One sale <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-1</li>
                <li>Sub Menu-1</li>
                <li>Sub Menu-1</li>
                <li>Sub Menu-1</li>
            </ul>
        </li>
        <li>Mobiles <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-2</li>
                <li>Sub Menu-2</li>
                <li>Sub Menu-2</li>
                <li>Sub Menu-2</li>
            </ul>
        </li>
        <li>Computers <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-3</li>
                <li>Sub Menu-3</li>
                <li>Sub Menu-3</li>
                <li>Sub Menu-3</li>
            </ul>
        </li>
        <li>Farniture <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-4</li>
                <li>Sub Menu-4</li>
                <li>Sub Menu-4</li>
                <li>Sub Menu-4</li>
            </ul>
        </li>
        <li>Tablets <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-5</li>
                <li>Sub Menu-5</li>
                <li>Sub Menu-5</li>
                <li>Sub Menu-5</li>
            </ul>
        </li>
        <li>Display <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-6</li>
                <li>Sub Menu-6</li>
                <li>Sub Menu-6</li>
                <li>Sub Menu-6</li>
            </ul>
        </li>
        <li>Laptop <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-7</li>
                <li>Sub Menu-7</li>
                <li>Sub Menu-7</li>
                <li>Sub Menu-7</li>
            </ul>
        </li>
        <li>Samsung <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-8</li>
                <li>Sub Menu-8</li>
                <li>Sub Menu-8</li>
                <li>Sub Menu-8</li>
            </ul>
        </li>
        <li>Xaomi <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-9</li>
                <li>Sub Menu-9</li>
                <li>Sub Menu-9</li>
                <li>Sub Menu-9</li>
            </ul>
        </li>
        <li>Mi <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-10</li>
                <li>Sub Menu-10</li>
                <li>Sub Menu-10</li>
                <li>Sub Menu-10</li>
            </ul>
        </li>
        <li>Lenovo <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-11</li>
                <li>Sub Menu-11</li>
                <li>Sub Menu-11</li>
                <li>Sub Menu-11</li>
            </ul>
        </li>
        <li>UPS <i class="fa fa-angle-right"></i> 
            <ul>
                <li>Sub Menu-12</li>
                <li>Sub Menu-12</li>
                <li>Sub Menu-12</li>
                <li>Sub Menu-12</li>
            </ul>
        </li>
    </ul>
</div>

templates/products_template/single.html
{% extends 'base.html' %}

{% block content %}

 <div class="container">
        <div class="card mb-3">
            <div class="row no-gutters">
                <div style="padding: 15px" class="col-md-4">
					{% for image in product.productimage_set.all %}
						{% if image.featured == True and image.active == True %}
						<img src="/media/{{image.image}}"
                        class="card-img" width="400" height="400" alt="...">
						{% endif %}
					{% endfor %}	
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            <div class="alert alert-primary" role="alert">
                            <strong>{{product.product_name}}</strong>
                        </div></h5>
                        <p class="card-text">{{product.description}}</p>

                        <h5 style="color: teal" class="card-subtitle mb-3">Price ৳: {{product.price}} Taka </h5>
                        
                        <div class="input-group mb-3">
							<form class="form" method="GET" action="{% url 'update_cart' product.slug %}">                    
						</div>						
								<button type="submit" class="btn btn-warning"><i class="fa fa-cart-plus"></i> Add to
								Cart</button>
							</form>                    
                    </div>
                                            
                    </div>
                </div>
            </div>
        </div>
    </div>
	
{% endblock %}